export * from './connection'
export {queries} from './querys'
export {pacquerys} from './querys/querys.paciente'
export {usuquerys} from './querys/querys.usuario'
export {consultasquerys} from './querys/querys.consultas'
export {turnosquerys} from './querys/querys.turnos'
export {planesquerys} from './querys/querys.planes'