 @api = http://localhost:3000

GET {{api}}/consulta/123

###

POST {{api}}/habitos
Content-Type: application/json

{
    "hab_descripcion": "prueba"
}

###

POST {{api}}/cabecerahabitos
Content-Type: application/json

{
    "habpac_nrohc": 1000,
    "habpac_observaciones": "",
    "habpac_idconsulta": 1
    
}

###

POST {{api}}/detallehabitos
Content-Type: application/json

{
    "dhabpac_id": 1,
    "dhabpac_idhabito": 2,
    "dhabpac_observaciones": ""
    
}

###

GET {{api}}/primeroshabitos/1000