 @api = http://localhost:3000

GET {{api}}/datosmiprogreso/1037

###

put {{api}}/modificarconsultageneral/160
Content-Type: application/json

{
    "cons_idturno":"160",
    "cons_observaciones":" 3ra consulta",
    "cons_edad":26,
    "cons_peso":75,
    "cons_talla":1.59,
    "cons_CCM":null,
    "cons_CCU":null,
    "cons_CCP":null,
    "cons_IMC":30.062101973814325,
    "cons_GC":null,
    "cons_GV":null,
    "cons_M":null,
    "cons_PBI":null
}

###

GET {{api}}/paciente/1000
###

GET {{api}}/empleado/leg=66685/doc=12312312
###


GET {{api}}/empleado/ap=Alfonzo/
###

DELETE {{api}}/pacientes/1004

###

PUT {{api}}/pacientes/1002
Content-Type: application/json

{
    "pac_nrodoc":"40245878",
    "pac_apellido":"Ramirez",
    "pac_nombre":"Juan",
    "pac_mutual":"Medifé",
    "pac_mutual2":"",
    "pac_telefono1":"3513456654",
    "pac_telefono2":"",
    "pac_fechanacimiento":"1991-03-14",
    "pac_correo":"jramirez@gmail.com",
    "pac_direccion":"Dean Funes 444"
}
