 @api = http://localhost:3000

GET {{api}}/usuarios

###

POST {{api}}/usuario
Content-Type: application/json

{
    "usu_usuario": 67404,
    "usu_clave": "12345",
    "usu_idperfil": "1",
    "usu_correo": ""
}

###

POST {{api}}/usuario/login
Content-Type: application/json

{
    "usu_usuario": 34554,
    "usu_clave": "mariela"
}

###

GET {{api}}/datosusuario/69669